### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by entalent** [mtanti/mtanti-phd#1]
I have read your paper _Transfer learning from language models to image caption
generators: Better models may not transfer better_ and found the result very interesting. When will the code for experiments in this paper release?

**Comment by mtanti** [comment]
Hi there! The pre-print paper you mention uses code from my PhD and this repository will contain all the code used in my PhD. I was waiting until I have a final draft ready before uploading the code, which will be soon, so that I wouldn't need to do more commits than necessary. Can you wait a couple of weeks? In the meantime you can ask me any questions you have on my pre-print paper via the email in the paper and I will be happen to answer you.

**Comment by mtanti** [comment]
Project has been uploaded. Sorry for the delay!
